### ISSUE TITLE
Estudar os dados sobre as obras da API

### ISSUE THREAD

**Issue by Beatriz-ge** [unb-mds/2024-2-SQUAD08#17]
# Descrição do Problema  
A equipe precisa compreender os dados fornecidos pela API sobre as obras para utilizá-los corretamente no desenvolvimento do sistema. Sem esse entendimento, há o risco de implementar funcionalidades que não atendam aos requisitos ou que causem erros na manipulação dos dados.

# Solução Proposta  
- Realizar uma análise detalhada dos dados retornados pela API sobre as obras, identificando os campos, tipos de dados e sua estrutura.  
- Verificar a consistência, os possíveis erros e as limitações nos dados fornecidos.  
- Documentar os principais atributos e como eles podem ser utilizados no projeto.  

# Tarefas  
- [ ] Fazer requisições à API para obter os dados relacionados às obras.  
- [ ] Identificar os campos presentes na resposta e seus respectivos tipos (exemplo: texto, número, lista, etc.).  
- [ ] Verificar a consistência dos dados e possíveis valores nulos ou ausentes.  
- [ ] Criar um documento explicando os campos principais e como eles podem ser utilizados no sistema.  
- [ ] Compartilhar os resultados do estudo com a equipe.  

# Critérios de Aceitação  
- [ ] Todos os campos e dados fornecidos pela API sobre as obras devem estar devidamente documentados.  
- [ ] Deve ser possível entender claramente como cada campo pode ser utilizado no sistema.  
- [ ] O estudo deve identificar potenciais problemas, como valores inconsistentes ou nulos, e sugerir soluções.  
- [ ] A equipe deve ter acesso a uma documentação clara e acessível sobre os dados.  

# Recursos  
- [[API Documentation](https://chatgpt.com/c/6722c1a8-45d0-8003-ab80-7d8c61663025#)](#) (substituir pelo link da documentação da API)  
- [[Postman Guide](https://learning.postman.com/docs/getting-started/introduction/)](https://learning.postman.com/docs/getting-started/introduction/)  
- [[JSON Data Types Overview](https://www.w3schools.com/js/js_json_datatypes.asp)](https://www.w3schools.com/js/js_json_datatypes.asp)  
- [[Good API Documentation Practices](https://www.redhat.com/en/topics/api/what-is-api-documentation)](https://www.redhat.com/en/topics/api/what-is-api-documentation)

**Comment by erickaalves** [comment]
Os devidos estudos sobre a api se encontram na pasta API da documentação do projeto, de forma a satisfazer as demandas da issue.
